-- TypeScript cheatsheet for DSA exercises.
-- Returned as a flat string[] displayed in the cheatsheet tab.

-- stylua: ignore
return {
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    " TYPESCRIPT CHEATSHEET                                           gt → learn tab",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "── TYPES ────────────────────────────────────────────────────────────────────────",
    "",
    "  number  string  boolean  null  undefined  never  unknown",
    "  let x: number = 1",
    "  let s: string | null = null                 // union",
    "  let arr: number[] = []                      // array",
    "  let t: [number, string] = [1, 'a']          // tuple",
    "  type Pair = [number, number]",
    "  Record<string, number>                      // object with typed values",
    "  Partial<T>                                  // all keys optional",
    "",
    "── ARRAY ────────────────────────────────────────────────────────────────────────",
    "",
    "  arr.push(x)              // append, returns new length",
    "  arr.pop()                // remove & return last",
    "  arr.shift()              // remove & return first   O(n)",
    "  arr.unshift(x)           // prepend                 O(n)",
    "  arr.slice(start, end)    // [start, end) copy, no mutation",
    "  arr.splice(i, n, ...xs)  // remove n at i, insert xs  mutates",
    "  arr.indexOf(x)           // first index or -1",
    "  arr.includes(x)          // boolean",
    "  arr.find(fn)             // first element where fn is true",
    "  arr.findIndex(fn)        // first index where fn is true",
    "  arr.filter(fn)           // new array of matching elements",
    "  arr.map(fn)              // new array of transformed elements",
    "  arr.reduce((acc,x)=>acc+x, 0)              // fold",
    "  arr.sort((a, b) => a - b)                  // ascending numeric sort  mutates",
    "  arr.flat()               // flatten one level",
    "  arr.fill(val, start, end)",
    "  arr.some(fn) / arr.every(fn)",
    "  Array.from({length: n}, (_, i) => i)       // [0, 1, ..., n-1]",
    "  Array.from(set)          // Set → Array",
    "",
    "── STRING ───────────────────────────────────────────────────────────────────────",
    "",
    "  s.split('')              // char array",
    "  s.split(' ')             // word array",
    "  s.trim()                 // strip whitespace",
    "  s.slice(start, end)      // substring [start, end)",
    "  s.padStart(n, '0')       // left-pad to length n",
    "  s.padEnd(n, ' ')",
    "  s.repeat(n)",
    "  s.startsWith(p) / s.endsWith(p)",
    "  s.includes(sub)",
    "  s.at(-1)                 // last character",
    "  s.charCodeAt(i)          // char → number  ('a' = 97)",
    "  String.fromCharCode(n)   // number → char",
    "  s.replace(re, sub)       // replace first (use /g for all)",
    "  s.toLowerCase() / s.toUpperCase()",
    "",
    "── MAP ──────────────────────────────────────────────────────────────────────────",
    "",
    "  const m = new Map<string, number>()",
    "  m.set(key, val)",
    "  m.get(key)               // undefined if missing",
    "  m.has(key)",
    "  m.delete(key)",
    "  m.size",
    "  for (const [k, v] of m.entries())",
    "  for (const k of m.keys())",
    "  for (const v of m.values())",
    "  m.get(key) ?? 0          // default to 0 if missing",
    "  m.set(key, (m.get(key) ?? 0) + 1)          // frequency count",
    "",
    "── SET ──────────────────────────────────────────────────────────────────────────",
    "",
    "  const s = new Set<number>()",
    "  s.add(x)",
    "  s.has(x)",
    "  s.delete(x)",
    "  s.size",
    "  [...s]                   // Set → Array",
    "  new Set(arr)             // Array → Set  (deduplication)",
    "",
    "── MATH ─────────────────────────────────────────────────────────────────────────",
    "",
    "  Math.min(a, b)  /  Math.max(a, b)",
    "  Math.min(...arr) / Math.max(...arr)         // spread array",
    "  Math.floor(x)  Math.ceil(x)  Math.round(x)",
    "  Math.abs(x)",
    "  Infinity   /   -Infinity                    // useful as initial min/max",
    "  x >> 1                   // Math.floor(x / 2)  integer divide",
    "  x & 1                    // x % 2             even/odd check",
    "",
    "── LOOPS ────────────────────────────────────────────────────────────────────────",
    "",
    "  for (const x of arr)",
    "  for (const [i, v] of arr.entries())",
    "  for (const key in obj)                      // own + inherited keys",
    "  for (const key of Object.keys(obj))",
    "",
    "── DSA PATTERNS ─────────────────────────────────────────────────────────────────",
    "",
    "  Stack (LIFO):",
    "    const stack: number[] = []",
    "    stack.push(x)  /  stack.pop()  /  stack.at(-1)   // peek",
    "",
    "  Queue (FIFO):",
    "    const queue: number[] = []",
    "    queue.push(x)  /  queue.shift()                   // O(n) shift",
    "",
    "  Two Pointers:",
    "    let l = 0, r = arr.length - 1",
    "    while (l < r) { ...; l++; r-- }",
    "",
    "  Sliding Window:",
    "    const seen = new Set<string>()",
    "    let l = 0",
    "    for (let r = 0; r < s.length; r++) {",
    "        while (seen.has(s[r])) { seen.delete(s[l]); l++ }",
    "        seen.add(s[r])",
    "    }",
    "",
    "  Binary Search:",
    "    let lo = 0, hi = arr.length - 1",
    "    while (lo <= hi) {",
    "        const mid = (lo + hi) >> 1",
    "        if (arr[mid] === target) return mid",
    "        else if (arr[mid] < target) lo = mid + 1",
    "        else hi = mid - 1",
    "    }",
    "",
    "  DFS (recursive):",
    "    function dfs(node: TreeNode | null): void {",
    "        if (!node) return",
    "        dfs(node.left); dfs(node.right)",
    "    }",
    "",
    "  BFS:",
    "    const queue: TreeNode[] = [root]",
    "    while (queue.length) {",
    "        const node = queue.shift()!",
    "        if (node.left) queue.push(node.left)",
    "        if (node.right) queue.push(node.right)",
    "    }",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
}
